server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
  - targets:
      - localhost
    labels:
      job: sit-email-scheduler-system
      __path__: /opt/swarm-data/path/logs/sit-email-scheduler-system/*log
  - targets:
      - localhost
    labels:
      job: sit-email-statement
      __path__: /opt/swarm-data/path/logs/sit-email-statement/*log
  - targets:
      - localhost
    labels:
      job: sit-email-gateway
      __path__: /opt/swarm-data/path/logs/sit-email-gateway/*log
  - targets:
      - localhost
    labels:
      job: sit-payroll-validation
      __path__: /opt/swarm-data/path/logs/sit-payroll-validation/*log
  - targets:
      - localhost
    labels:
      job: sit-bic-swiftcode
      __path__: /opt/swarm-data/path/logs/sit-bic-swiftcode/*log




